config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  # Session routes
  get 'login', to: 'session#new'
  post 'session/create', to: "session#create"
  get 'logout', to: 'session#destroy'

  # Pages routes
  get '/about', to: 'pages#about'

  # Post routes 
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

	validates :title, :description, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	def authentication_required
	  if !logged_in?
	    flash[:message] = "Must be logged in create a post"
	    redirect_to login_path
	  end
	end

	def login(user)
		session[:user_id] = user.id
	end

	def logged_in?
		!!current_user
	end

	def current_user
		@current_user ||= User.find_by(:id => session[:user_id])
	end

	helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index 
		@posts = Post.limit(7).order(:id)
		renderer = Redcarpet::Render::HTML.new(hard_wrap: true)
		@markdown = Redcarpet::Markdown.new(renderer)
	end

	def about 
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authentication_required, only: [:new, :create, :update, :edit, :destroy]


	def index
	end

	def show
		@post = Post.find(params[:id])
		renderer = Redcarpet::Render::HTML.new(hard_wrap: true)
		@markdown = Redcarpet::Markdown.new(renderer)
	end

	def new
		@post = Post.new
	end 

	def create
		@post = Post.create(post_params)
		redirect_to post_path(@post)
	end 

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
	end

	private

	def post_params
		params.require(:post).permit(:id, :title, :description, :content)
	end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.find_by(username: session_params[:username])
    	if @user && @user.authenticate(session_params[:password])
    		login(@user)
    		redirect_to root_path
    	else
    		flash[:message] = "Can not find and/or authenticate user"
        redirect_to login_path
    	end
	end

	def destroy
		session.clear
		redirect_to root_path
	end

	private

	def session_params
		params.require(:user).permit(:username, :password)
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_controller_helper.rb
module SessionControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nic Travis Codes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <div class="sidebar box">
        <div class="logo-d iv"><a href="/"><%= image_tag 'me.jpeg', class: 'logo'%></a></div>
        <div class="about-div">
          <h2>About</h2>
          <p>I am freelance web developer, currently living in sunny Bangkok, TH. I focus on Ruby, Rails, React, Redux, and other things that begin with R. I also do music stuff. <%= link_to 'more', about_path %> </p>
          <p>Thank you for visiting.</p>
        </div>
        <% if current_user %>
          <%= link_to "Create", new_post_path %>
          <%= link_to "Log out", logout_path %>
        <% else %>
          <%= link_to "Are you me?", login_path %>
        <% end %>
      </div>

      <div class="content box">
        <%= yield %>
      </div>

      <div class="footer box">
          <%= link_to '<- Newer', root_path %>
          <%= link_to 'Older ->', posts_path %>
      </div>

    </div>

  <div class="side-text">
    <span>&copy Nic Travis Codes</span>
  </div>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>

app/views/pages/index.html.erb
<div class="posts-wrapper">

	<% @posts.each_with_index do |post, index| %>
		<% if index == 0 %>
			<div class="big-post post-box">
				<h2><%= link_to post.title, post_path(post) %></h2>
				<span class='post-date'><%= Date.parse(post.created_at.to_s).strftime('%B %d, %Y')  %></span>
				<p><%= post.description %></p>
				<%= @markdown.render(post.content).html_safe %>
			</div>
		<% elsif index > 0 || index < 3%>
			<div class="mid-post post-box">
				<h2><%= link_to post.title, post_path(post) %></h2>
				<span class='post-date'><%= Date.parse(post.created_at.to_s).strftime('%B %d, %Y')  %></span>
				<p><%= post.description %></p>
				<%= @markdown.render(post.content).html_safe %>
			</div>
		<% else %>
			<div class="small-post post-box">
				<h2><%= link_to post.title, post_path(post) %></h2>
				<span class='post-date'><%= Date.parse(post.created_at.to_s).strftime('%B %d, %Y')  %></span>
				<p><%= post.description %></p>
				<%= @markdown.render(post.content).html_safe %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/posts/destroy.html.erb
<h1>Your post has been deleted</h1>

app/views/posts/edit.html.erb
<div class="new-post-form">
<%= form_for @post do |f| %>
	<h1>Create a New Post</h1>
	<h3>Title</h3>	
	<p><%= f.text_field :title,  size: "100x12" %></p>
	<h3>Description</h3>	
	<p><%= f.text_field :description, size: "100x12" %></p>
	<h3>Content</h3>
	<p><%= f.text_area :content, size: "100x100" %></p>
	<%= f.submit "Save" %>
<% end %>
</div>

app/views/posts/index.html.erb
<h1>All Posts - 7</h1>

app/views/posts/show.html.erb
<% if current_user %>
<%= link_to 'Edit', edit_post_path(@post) %>
<%= button_to "delete", post_path(@post), method: 'delete' %>
<% end %>
<h1><%= @post.title %></h1>
<h2><%= @post.description %></h2>
<%= @markdown.render(@post.content).html_safe %>

app/views/session/new.html.erb
<h1>Prove it</h1>

<% if flash[:message].present? %>
	<ul class="errors">
		<li><%= flash[:message] %></li>
	</ul>
<% end %>

<%= form_for @user, url: session_create_path do |f| %>
	<p>Username</p>
	<p><%= f.text_field :username %></p>
	<p>Password</p>
	<p><%= f.password_field :password %></p>
	<p><%= f.submit "Log In" %></p>
<% end %>